-- AlterTable
ALTER TABLE "Sale" ADD COLUMN     "paymentMethod" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "purchaseFeedback" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "region" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "saleDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "salesChannel" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "totalRevenue" DOUBLE PRECISION NOT NULL DEFAULT 0;
